name: digital_khata
description: "digital_khata clone"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.8.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  go_router: ^16.2.1
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  equatable: ^2.0.5

  # Supabase
  supabase_flutter: ^2.8.0
  qr_flutter: ^4.1.0

  # State Management
  flutter_riverpod: ^2.6.1

  # Biometrics, Platform Services & URL Launching
  local_auth: ^2.3.0
  url_launcher: ^6.3.1
  flutter_secure_storage: ^9.2.2
  crypto: ^3.0.6

  # PDF & Excel Document Exports
  pdf: ^3.11.1
  excel: ^4.0.6

  # Barcode & Sharing Utilities
  barcode_widget: ^2.0.4
  barcode: ^2.2.8
  share_plus: ^9.0.0
  path_provider: ^2.1.0

  # Google Sign In & Drive API for Cloud Backups
  google_sign_in: ^6.2.1
  googleapis: ^13.1.0
  googleapis_auth: ^1.6.0

  # Utilities
  image_picker: ^1.2.0
  http: ^1.4.0
  uuid: ^4.5.1
  fl_chart: ^0.65.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/payment_methods/visa.png
    - assets/payment_methods/mastercard.png
    - assets/payment_methods/jazzcash.png
    - assets/payment_methods/easypaisa.png
    - assets/payment_methods/cash.png
    - assets/payment_methods/bank.png
    - assets/auth_bg.png
    - assets/logo.png
  fonts:
    - family: Kalimati
      fonts:
        - asset: assets/fonts/Kalimati.otf